#! /bin/sh
# plantfetch

# Colors
c0='[0m'
c1='[31;1m'
c2='[32m'
c3='[33m'
c4='[34m'
c5='[35m'
c6='[36m'
c7='[37m'
c8='[38m'
c9='^[[37m'
c10='^[[43m'

# Art
artR1="${c1}  _ _    "
artR2="${c1} (_\_)   "
artR3="${c1}(__*__)  "
artR4="${c1} (_/_)   "
artR5="${c2} \ |     "
artR6="${c2}  \|/    "
artRp1="${c5}  _ _    "
artRp2="${c5} (_\_)   "
artRp3="${c5}(__*__)  "
artRp4="${c5} (_/_)   "
artRp5="${c2} \ |     "
artRp6="${c2}  \|/    "
artRb1="${c4}  _ _    "
artRb2="${c4} (_\_)   "
artRb3="${c4}(__*__)  "
artRb4="${c4} (_/_)   "
artRb5="${c2} \ |     "
artRb6="${c2}  \|/    "
artRy1="${c3}  _ _    "
artRy2="${c3} (_\_)   "
artRy3="${c3}(__*__)  "
artRy4="${c3} (_/_)   "
artRy5="${c2} \ |     "
artRy6="${c2}  \|/    "
artRc1="${c6}  _ _    "
artRc2="${c6} (_\_)   "
artRc3="${c6}(__*__)  "
artRc4="${c6} (_/_)   "
artRc5="${c2} \ |     "
artRc6="${c2}  \|/    "

# Print
cat <<-EOF
${artR1} ${artRy1} ${artRc1} ${artRb1} ${artRp1}
${artR2} ${artRy2} ${artRc2} ${artRb2} ${artRp2}
${artR3} ${artRy3} ${artRc3} ${artRb3} ${artRp3}
${artR4} ${artRy4} ${artRc4} ${artRb4} ${artRp4}
${artR5} ${artRy5} ${artRc5} ${artRb5} ${artRp5}
${artR6} ${artRy6} ${artRc6} ${artRb6} ${artRp6}

EOF
