#! /bin/sh
# plantfetch

# Packages
if command -v pacman >/dev/null
then
    pkg="$(pacman -Qq | wc -l)"
fi

# Get user
user="${USER-$(id -u -n)}"

# Get host
host="$(uname -n)"

# Get OS
. /etc/os-release
os="$NAME"

# Uptime
IFS=. read -r s _ < /proc/uptime
# Convert the uptime from seconds into days, hours and minutes.
d=$((s / 60 / 60 / 24))
h=$((s / 60 / 60 % 24))
m=$((s / 60 % 60))
# Only append days, hours and minutes if they're non-zero.
case "$d" in ([!0]*) uptime="${uptime}${d}d "; esac
case "$h" in ([!0]*) uptime="${uptime}${h}h "; esac
case "$m" in ([!0]*) uptime="${uptime}${m}m "; esac

# Shell
shell="${SHELL##*/}"

# Display protocol
[ "$DISPLAY" ] && displayprot="x11"
[ "$WAYLAND_DISPLAY" ] && displayprot="wayland"
[ ! "$displayprot" ] && displayprot="tty"

# Window Manager
wm="$XDG_CURRENT_DESKTOP"
[ "$wm" ] || wm="$DESKTOP_SESSION"

[ ! "$wm" ] && [ "$DISPLAY" ] && command -v xprop >/dev/null && {
    id=$(xprop -root -notype _NET_SUPPORTING_WM_CHECK)
    id=${id##* }
    wm=$(xprop -id "$id" -notype -len 100 -f _NET_WM_NAME 8t |
        grep '^_NET_WM_NAME' | cut -d\" -f 2)
}

# Non-EWH WMs
[ ! "$wm" ] || [ "$wm" = "non-EWH" ] &&
    wm=$(
        ps -e | grep -m 1 -o \
            -e "sway" \
            -e "kiwmi" \
            -e "wayfire" \
            -e "sowm" \
            -e "catwm" \
            -e "fvwm" \
            -e "dwm" \
            -e "2bwm" \
            -e "monsterwm" \
            -e "tinywm" \
            -e "xmonad"
    )

[ ! "$wm" ] && wm="none"

# Colors
c0='[0m'
c1='[31;1m'
c2='[32m'
c3='[33m'
c4='[34m'
c5='[35m'
c6='[36m'
c7='[37m'
c8='[38m'
c9='^[[37m'
c10='^[[43m'

# Art
artR1="${c1}  _ _    "
artR2="${c1} (_\_)   "
artR3="${c1}(__*__)  "
artR4="${c1} (_/_)   "
artR5="${c2} \ |     "
artR6="${c2}  \|/    "
artRp1="${c5}  _ _    "
artRp2="${c5} (_\_)   "
artRp3="${c5}(__*__)  "
artRp4="${c5} (_/_)   "
artRp5="${c2} \ |     "
artRp6="${c2}  \|/    "
artRb1="${c4}  _ _    "
artRb2="${c4} (_\_)   "
artRb3="${c4}(__*__)  "
artRb4="${c4} (_/_)   "
artRb5="${c2} \ |     "
artRb6="${c2}  \|/    "
artRy1="${c3}  _ _    "
artRy2="${c3} (_\_)   "
artRy3="${c3}(__*__)  "
artRy4="${c3} (_/_)   "
artRy5="${c2} \ |     "
artRy6="${c2}  \|/    "
artRc1="${c6}  _ _    "
artRc2="${c6} (_\_)   "
artRc3="${c6}(__*__)  "
artRc4="${c6} (_/_)   "
artRc5="${c2} \ |     "
artRc6="${c2}  \|/    "

# Print
cat <<-EOF
${artR1} ${artRy1} ${artRc1} ${artRb1} ${artRp1}
${artR2} ${artRy2} ${artRc2} ${artRb2} ${artRp2}
${artR3} ${artRy3} ${artRc3} ${artRb3} ${artRp3}
${artR4} ${artRy4} ${artRc4} ${artRb4} ${artRp4}
${artR5} ${artRy5} ${artRc5} ${artRb5} ${artRp5}
${artR6} ${artRy6} ${artRc6} ${artRb6} ${artRp6}

EOF
